CREATE TABLE rider (
    id                  BIGINT       NOT NULL AUTO_INCREMENT,
    rider_no            VARCHAR(32)  NOT NULL              COMMENT '骑手工号 QS+6位',
    name                VARCHAR(64)  NOT NULL,
    phone               VARCHAR(20)  NOT NULL,
    password_hash       VARCHAR(100) NOT NULL              COMMENT 'BCrypt',
    must_change_password TINYINT(1)  NOT NULL DEFAULT 1,
    avatar_url          VARCHAR(512) NULL,
    id_card_masked      VARCHAR(32)  NULL                  COMMENT '身份证脱敏 3***********1234',
    role                VARCHAR(24)  NOT NULL DEFAULT 'RIDER' COMMENT 'RIDER / RIDER_CAPTAIN',
    account_status      VARCHAR(24)  NOT NULL DEFAULT 'ACTIVE' COMMENT 'ACTIVE/SUSPENDED/RESIGNED',
    work_status         VARCHAR(24)  NOT NULL DEFAULT 'OFF_DUTY' COMMENT 'OFF_DUTY/ON_DUTY/RESTING/BUSY',
    health_cert_no      VARCHAR(64)  NULL,
    health_cert_expire_at DATE       NULL,
    vehicle_plate       VARCHAR(32)  NULL                  COMMENT '电动车车牌',
    vehicle_type        VARCHAR(24)  NOT NULL DEFAULT 'EBIKE' COMMENT 'EBIKE/BICYCLE/WALK/CAR',
    max_concurrent_task INT          NOT NULL DEFAULT 8    COMMENT '同时可带任务数上限',
    capacity_weight_kg  DECIMAL(10,3) NOT NULL DEFAULT 30.000,
    insulated_box_count INT          NOT NULL DEFAULT 1,
    probation           TINYINT(1)   NOT NULL DEFAULT 1    COMMENT '新手保护期',
    hired_at            DATE         NULL,
    service_score       INT          NOT NULL DEFAULT 100  COMMENT '服务分，初始100',
    level_code          VARCHAR(24)  NOT NULL DEFAULT 'L1',
    total_task_count    INT          NOT NULL DEFAULT 0,
    on_time_task_count  INT          NOT NULL DEFAULT 0,
    location_consent_at DATETIME(6)  NULL                  COMMENT 'PIPL 单独同意时间，NULL 则禁止采集',
    location_consent_version VARCHAR(32) NULL,
    remark              VARCHAR(512) NULL,
    created_at          DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at          DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    deleted_at          DATETIME(6)  NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_rider_no (rider_no),
    UNIQUE KEY uk_rider_phone (phone),
    KEY idx_rider_work_status (work_status, account_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE rider_session (
    id              BIGINT       NOT NULL AUTO_INCREMENT,
    rider_id        BIGINT       NOT NULL,
    access_token    VARCHAR(96)  NOT NULL   COMMENT 'rider_ 前缀',
    refresh_token   VARCHAR(96)  NOT NULL,
    device_id       VARCHAR(128) NULL,
    access_expire_at  DATETIME(6) NOT NULL,
    refresh_expire_at DATETIME(6) NOT NULL,
    revoked_at      DATETIME(6)  NULL,
    revoke_reason   VARCHAR(128) NULL,
    last_active_at  DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    client_ip       VARCHAR(64)  NULL,
    created_at      DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_session_access (access_token),
    UNIQUE KEY uk_session_refresh (refresh_token),
    KEY idx_session_rider (rider_id, revoked_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE rider_device (
    id              BIGINT       NOT NULL AUTO_INCREMENT,
    rider_id        BIGINT       NOT NULL,
    device_id       VARCHAR(128) NOT NULL,
    manufacturer    VARCHAR(64)  NULL,
    model           VARCHAR(64)  NULL,
    os_version      VARCHAR(32)  NULL,
    app_version     VARCHAR(32)  NULL,
    push_registration_id VARCHAR(128) NULL COMMENT '极光 RegistrationId',
    push_vendor     VARCHAR(32)  NULL      COMMENT 'XIAOMI/HUAWEI/OPPO/VIVO/HONOR/JPUSH',
    battery_optimization_ignored TINYINT(1) NOT NULL DEFAULT 0,
    notification_enabled TINYINT(1) NOT NULL DEFAULT 0,
    background_location_granted TINYINT(1) NOT NULL DEFAULT 0,
    keepalive_guide_done TINYINT(1) NOT NULL DEFAULT 0,
    last_seen_at    DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    created_at      DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at      DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_device (rider_id, device_id),
    KEY idx_device_push (push_registration_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE rider_shift (
    id                  BIGINT      NOT NULL AUTO_INCREMENT,
    rider_id            BIGINT      NOT NULL,
    shift_date          DATE        NOT NULL,
    on_duty_at          DATETIME(6) NOT NULL,
    off_duty_at         DATETIME(6) NULL,
    off_duty_reason     VARCHAR(64) NULL      COMMENT 'MANUAL/FATIGUE_FORCED/ADMIN/TIMEOUT',
    online_seconds      INT         NOT NULL DEFAULT 0,
    continuous_seconds  INT         NOT NULL DEFAULT 0 COMMENT '连续接单时长，休息后清零',
    rest_total_seconds  INT         NOT NULL DEFAULT 0,
    last_rest_at        DATETIME(6) NULL,
    fatigue_4h_notified_at  DATETIME(6) NULL,
    fatigue_8h_confirmed_at DATETIME(6) NULL COMMENT '骑手确认继续接单的时间，合规留证',
    dispatch_paused_until   DATETIME(6) NULL COMMENT '疲劳后停止派单截止时间',
    task_count          INT         NOT NULL DEFAULT 0,
    delivered_count     INT         NOT NULL DEFAULT 0,
    on_time_count       INT         NOT NULL DEFAULT 0,
    exception_count     INT         NOT NULL DEFAULT 0,
    mileage_meters      INT         NOT NULL DEFAULT 0,
    earning_amount      INT         NOT NULL DEFAULT 0,
    helmet_confirmed    TINYINT(1)  NOT NULL DEFAULT 0,
    created_at          DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at          DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    KEY idx_shift_rider_date (rider_id, shift_date),
    KEY idx_shift_open (rider_id, off_duty_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
