CREATE TABLE delivery_task (
    id                  BIGINT       NOT NULL AUTO_INCREMENT,
    task_no             VARCHAR(32)  NOT NULL  COMMENT 'PS+yyyyMMdd+6位序号',
    order_id            BIGINT       NOT NULL  COMMENT '软引用 JSON 快照中的订单 id',
    order_no            VARCHAR(32)  NOT NULL,
    wave_id             BIGINT       NULL,
    rider_id            BIGINT       NULL,
    status              VARCHAR(24)  NOT NULL DEFAULT 'PENDING',
    -- 收货信息快照
    receiver_name       VARCHAR(64)  NOT NULL,
    receiver_phone      VARCHAR(20)  NOT NULL  COMMENT '真实号码，仅服务端与后台可见',
    receiver_phone_masked VARCHAR(20) NOT NULL COMMENT '138****5678，下发给 App',
    address_detail      VARCHAR(512) NOT NULL,
    address_lat         DECIMAL(10,7) NULL,
    address_lng         DECIMAL(10,7) NULL,
    geocode_source      VARCHAR(24)  NULL      COMMENT 'USER_PICK/GEOCODE/MANUAL',
    area_label          VARCHAR(128) NULL      COMMENT '来自 DeliveryAddressIntelligence',
    building_label      VARCHAR(64)  NULL,
    group_key           VARCHAR(160) NULL,
    unit_no             INT          NULL,
    floor_no            INT          NULL,
    room_no             VARCHAR(32)  NULL,
    -- 货物信息
    item_count          INT          NOT NULL DEFAULT 0,
    total_weight_kg     DECIMAL(10,3) NOT NULL DEFAULT 0.000,
    cold_chain_level    VARCHAR(24)  NOT NULL DEFAULT 'NORMAL' COMMENT 'NORMAL/CHILLED/FROZEN',
    package_count       INT          NOT NULL DEFAULT 1,
    goods_summary       VARCHAR(512) NULL,
    customer_remark     VARCHAR(512) NULL,
    delivery_instruction VARCHAR(128) NULL     COMMENT '放门口/放前台/当面签收',
    -- 时间窗与 ETA
    delivery_date       DATE         NOT NULL,
    slot_label          VARCHAR(64)  NULL,
    window_start_at     DATETIME(6)  NULL,
    window_end_at       DATETIME(6)  NULL,
    promised_at         DATETIME(6)  NULL      COMMENT '对顾客承诺的送达时间',
    eta_at              DATETIME(6)  NULL      COMMENT '当前预估送达时间',
    eta_lower_at        DATETIME(6)  NULL,
    eta_upper_at        DATETIME(6)  NULL,
    eta_updated_at      DATETIME(6)  NULL,
    extra_time_seconds  INT          NOT NULL DEFAULT 0 COMMENT '累计补时',
    extra_time_reason   VARCHAR(256) NULL,
    -- 履约时间戳
    picked_ready_at     DATETIME(6)  NULL      COMMENT '拣货完成，派单触发点',
    assigned_at         DATETIME(6)  NULL,
    accepted_at         DATETIME(6)  NULL,
    picked_up_at        DATETIME(6)  NULL,
    departed_at         DATETIME(6)  NULL,
    arrived_at          DATETIME(6)  NULL,
    delivered_at        DATETIME(6)  NULL,
    closed_at           DATETIME(6)  NULL,
    -- 度量
    plan_distance_meters INT         NOT NULL DEFAULT 0,
    actual_distance_meters INT       NOT NULL DEFAULT 0,
    handoff_seconds     INT          NULL      COMMENT '到达到送达的耗时，喂给楼栋学习',
    is_on_time          TINYINT(1)   NULL,
    overtime_seconds    INT          NOT NULL DEFAULT 0,
    -- 派单元数据
    dispatch_mode       VARCHAR(24)  NULL      COMMENT 'AUTO/MANUAL/REASSIGN',
    dispatch_score      DECIMAL(10,4) NULL,
    reassign_count      INT          NOT NULL DEFAULT 0,
    hold_until_at       DATETIME(6)  NULL      COMMENT '压单窗口截止',
    priority            INT          NOT NULL DEFAULT 0 COMMENT '越大越优先',
    current_exception_id BIGINT      NULL,
    delivery_fee_amount INT          NOT NULL DEFAULT 0 COMMENT '顾客支付的配送费快照',
    created_at          DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at          DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_task_no (task_no),
    UNIQUE KEY uk_task_order (order_id),
    KEY idx_task_status (status, delivery_date),
    KEY idx_task_rider (rider_id, status),
    KEY idx_task_wave (wave_id),
    KEY idx_task_pending (status, hold_until_at),
    KEY idx_task_eta (status, eta_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE delivery_task_event (
    id              BIGINT       NOT NULL AUTO_INCREMENT,
    task_id         BIGINT       NOT NULL,
    task_no         VARCHAR(32)  NOT NULL,
    wave_id         BIGINT       NULL,
    event_type      VARCHAR(32)  NOT NULL COMMENT 'STATUS_CHANGE/ASSIGN/REASSIGN/EXCEPTION/ETA_UPDATE/NOTE',
    from_status     VARCHAR(24)  NULL,
    to_status       VARCHAR(24)  NULL,
    operator_type   VARCHAR(24)  NOT NULL COMMENT 'RIDER/ADMIN/SYSTEM/CUSTOMER',
    operator_id     BIGINT       NULL,
    operator_name   VARCHAR(64)  NULL,
    reason          VARCHAR(256) NULL,
    detail_json     JSON         NULL,
    lat             DECIMAL(10,7) NULL COMMENT '事件发生时骑手位置',
    lng             DECIMAL(10,7) NULL,
    client_event_at DATETIME(6)  NULL COMMENT '客户端原始时间戳，离线补传时与 created_at 不同',
    created_at      DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    KEY idx_event_task (task_id, id),
    KEY idx_event_time (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE delivery_wave (
    id                  BIGINT       NOT NULL AUTO_INCREMENT,
    wave_no             VARCHAR(32)  NOT NULL COMMENT 'BC+yyyyMMdd+4位',
    rider_id            BIGINT       NULL,
    status              VARCHAR(24)  NOT NULL DEFAULT 'PLANNING'
                                     COMMENT 'PLANNING/ASSIGNED/PICKING/DELIVERING/COMPLETED/CANCELLED',
    delivery_date       DATE         NOT NULL,
    task_count          INT          NOT NULL DEFAULT 0,
    completed_count     INT          NOT NULL DEFAULT 0,
    total_weight_kg     DECIMAL(10,3) NOT NULL DEFAULT 0.000,
    total_item_count    INT          NOT NULL DEFAULT 0,
    max_cold_chain_level VARCHAR(24) NOT NULL DEFAULT 'NORMAL',
    plan_distance_meters INT         NOT NULL DEFAULT 0,
    plan_duration_seconds INT        NOT NULL DEFAULT 0,
    actual_distance_meters INT       NOT NULL DEFAULT 0,
    plan_return_at      DATETIME(6)  NULL COMMENT '预计返店时间',
    route_plan_id       BIGINT       NULL,
    optimizer_name      VARCHAR(48)  NULL COMMENT 'GREEDY_2OPT/JSPRIT/AMAP',
    matrix_provider     VARCHAR(48)  NULL COMMENT 'HAVERSINE/AMAP/TENCENT',
    assigned_at         DATETIME(6)  NULL,
    started_at          DATETIME(6)  NULL,
    completed_at        DATETIME(6)  NULL,
    created_at          DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at          DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_wave_no (wave_no),
    KEY idx_wave_rider (rider_id, status),
    KEY idx_wave_date (delivery_date, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE delivery_wave_stop (
    id                  BIGINT       NOT NULL AUTO_INCREMENT,
    wave_id             BIGINT       NOT NULL,
    task_id             BIGINT       NOT NULL,
    seq_no              INT          NOT NULL COMMENT '从1开始的配送顺序',
    original_seq_no     INT          NOT NULL COMMENT '系统规划的原始顺序，骑手调整后对比学习',
    lat                 DECIMAL(10,7) NULL,
    lng                 DECIMAL(10,7) NULL,
    leg_distance_meters INT          NOT NULL DEFAULT 0 COMMENT '上一站到本站',
    leg_duration_seconds INT         NOT NULL DEFAULT 0,
    handoff_estimate_seconds INT     NOT NULL DEFAULT 0 COMMENT '本站预估交付耗时',
    plan_arrive_at      DATETIME(6)  NULL,
    plan_depart_at      DATETIME(6)  NULL,
    actual_arrive_at    DATETIME(6)  NULL,
    actual_depart_at    DATETIME(6)  NULL,
    adjusted_by_rider   TINYINT(1)   NOT NULL DEFAULT 0,
    created_at          DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at          DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_stop_wave_task (wave_id, task_id),
    KEY idx_stop_wave_seq (wave_id, seq_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
