CREATE TABLE delivery_config (
    config_key      VARCHAR(96)  NOT NULL,
    config_value    VARCHAR(1024) NOT NULL,
    value_type      VARCHAR(16)  NOT NULL DEFAULT 'STRING' COMMENT 'STRING/INT/DECIMAL/BOOL/JSON',
    category        VARCHAR(48)  NOT NULL DEFAULT 'GENERAL',
    display_name    VARCHAR(128) NOT NULL,
    description     VARCHAR(512) NULL,
    min_value       VARCHAR(32)  NULL,
    max_value       VARCHAR(32)  NULL,
    editable        TINYINT(1)   NOT NULL DEFAULT 1,
    updated_by      VARCHAR(64)  NULL,
    updated_at      DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (config_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE delivery_zone (
    id              BIGINT       NOT NULL AUTO_INCREMENT,
    zone_name       VARCHAR(64)  NOT NULL,
    zone_type       VARCHAR(24)  NOT NULL DEFAULT 'NORMAL'
        COMMENT 'NORMAL/FAR/DIFFICULT/PRIORITY —— 均为标注属性，用于补时/加价/提示，任何一种都不会阻止派单',
    polygon_json    JSON         NULL COMMENT '[[lat,lng],...]',
    center_lat      DECIMAL(10,7) NULL,
    center_lng      DECIMAL(10,7) NULL,
    radius_meters   INT          NULL COMMENT '圆形围栏时使用',
    extra_time_seconds INT       NOT NULL DEFAULT 0 COMMENT '该区域额外补时',
    extra_fee_amount INT         NOT NULL DEFAULT 0,
    enabled         TINYINT(1)   NOT NULL DEFAULT 1,
    sort_order      INT          NOT NULL DEFAULT 0,
    remark          VARCHAR(512) NULL,
    created_at      DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at      DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    KEY idx_zone_type (zone_type, enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE rider_message (
    id              BIGINT       NOT NULL AUTO_INCREMENT,
    rider_id        BIGINT       NULL COMMENT 'NULL 表示全员广播',
    message_type    VARCHAR(32)  NOT NULL
        COMMENT 'TASK_ASSIGNED/TASK_REASSIGNED/TASK_CANCELLED/ANNOUNCEMENT/SCORE/SETTLEMENT/APPEAL_RESULT/FATIGUE/SYSTEM',
    title           VARCHAR(128) NOT NULL,
    content         VARCHAR(1024) NOT NULL,
    link_type       VARCHAR(32)  NULL COMMENT 'TASK/WAVE/SETTLEMENT/APPEAL/NONE',
    link_target     VARCHAR(64)  NULL,
    priority        VARCHAR(16)  NOT NULL DEFAULT 'NORMAL' COMMENT 'LOW/NORMAL/HIGH/URGENT',
    need_voice      TINYINT(1)   NOT NULL DEFAULT 0 COMMENT '是否语音播报',
    need_ack        TINYINT(1)   NOT NULL DEFAULT 0 COMMENT '是否需要骑手确认',
    acked_at        DATETIME(6)  NULL,
    read_at         DATETIME(6)  NULL,
    push_status     VARCHAR(24)  NOT NULL DEFAULT 'PENDING'
                                 COMMENT 'PENDING/SENT/FAILED/SKIPPED',
    push_error      VARCHAR(256) NULL,
    expire_at       DATETIME(6)  NULL,
    created_at      DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    KEY idx_message_rider (rider_id, read_at, created_at),
    KEY idx_message_push (push_status, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE privacy_number_binding (
    id              BIGINT       NOT NULL AUTO_INCREMENT,
    task_id         BIGINT       NOT NULL,
    rider_id        BIGINT       NOT NULL,
    provider        VARCHAR(32)  NOT NULL DEFAULT 'ALIYUN_AXB',
    subscription_id VARCHAR(64)  NULL COMMENT '服务商返回的绑定 id',
    privacy_number  VARCHAR(20)  NOT NULL COMMENT 'X 号码',
    phone_a         VARCHAR(20)  NOT NULL COMMENT '骑手',
    phone_b         VARCHAR(20)  NOT NULL COMMENT '顾客',
    status          VARCHAR(24)  NOT NULL DEFAULT 'ACTIVE'
                                 COMMENT 'ACTIVE/RELEASED/FAILED/DEGRADED',
    call_count      INT          NOT NULL DEFAULT 0,
    expire_at       DATETIME(6)  NOT NULL,
    released_at     DATETIME(6)  NULL,
    created_at      DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    KEY idx_privacy_task (task_id, status),
    KEY idx_privacy_expire (status, expire_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE delivery_rating (
    id              BIGINT       NOT NULL AUTO_INCREMENT,
    task_id         BIGINT       NOT NULL,
    order_id        BIGINT       NOT NULL,
    rider_id        BIGINT       NOT NULL,
    user_id         BIGINT       NOT NULL,
    star            INT          NOT NULL COMMENT '1-5',
    tags            VARCHAR(256) NULL COMMENT '逗号分隔：准时/礼貌/包装完好/态度好',
    comment         VARCHAR(512) NULL,
    is_negative     TINYINT(1)   NOT NULL DEFAULT 0,
    waived          TINYINT(1)   NOT NULL DEFAULT 0 COMMENT '因异常上报成立而免责',
    waive_reason    VARCHAR(256) NULL,
    created_at      DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_rating_task (task_id),
    KEY idx_rating_rider (rider_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO delivery_config
    (config_key, config_value, value_type, category, display_name, description, min_value, max_value)
VALUES
    ('store.lat', '38.383423', 'DECIMAL', 'STORE', '门店纬度', '门店纬度，GCJ-02。当前为兴泾镇中心的近似值，请在高德地图上长按门店位置取精确坐标后在本页修改', '-90', '90'),
    ('store.lng', '106.096144', 'DECIMAL', 'STORE', '门店经度', '门店经度，GCJ-02。当前为兴泾镇中心的近似值，请在高德地图上长按门店位置取精确坐标后在本页修改', '-180', '180'),
    ('store.service_radius_meters', '3000', 'INT', 'STORE', '远单标记半径（米）', '不是配送范围限制。仅用于远单标记与调度台提示，超出此值的订单照常派送', '0', '50000'),
    ('store.gps_sanity_radius_meters', '200000', 'INT', 'STORE', 'GPS 异常点阈值（米）', 'GPS 异常点识别阈值（200 km）。这是数据清洗不是业务规则，超出必然是定位漂移', '1000', '1000000'),
    ('dispatch.enabled', 'true', 'BOOL', 'DISPATCH', '自动派单总开关', '自动派单总开关', NULL, NULL),
    ('dispatch.hold_window_seconds', '120', 'INT', 'DISPATCH', '压单窗口（秒）', '压单窗口 0-180', '0', '180'),
    ('dispatch.loop_interval_seconds', '5', 'INT', 'DISPATCH', '调度循环间隔（秒）', '调度循环间隔', '1', '60'),
    ('dispatch.max_tasks_per_wave', '8', 'INT', 'DISPATCH', '单波次最大单量', '单波次最大单量', '1', '20'),
    ('dispatch.max_wave_distance_meters', '8000', 'INT', 'DISPATCH', '单波次最大里程（米）', '单波次最大里程', '1000', '50000'),
    ('dispatch.max_wave_duration_seconds', '3600', 'INT', 'DISPATCH', '单波次最大时长（秒）', '单波次最大时长', '600', '14400'),
    ('dispatch.batching_radius_meters', '500', 'INT', 'DISPATCH', '合单聚类半径（米）', '合单聚类半径', '50', '5000'),
    ('dispatch.weight_added_distance', '0.35', 'DECIMAL', 'DISPATCH', '顺路度权重', '顺路度权重', '0', '1'),
    ('dispatch.weight_overtime_risk', '0.30', 'DECIMAL', 'DISPATCH', '超时风险权重', '超时风险权重', '0', '1'),
    ('dispatch.weight_load_balance', '0.15', 'DECIMAL', 'DISPATCH', '负载均衡权重', '负载均衡权重', '0', '1'),
    ('dispatch.weight_cold_chain', '0.15', 'DECIMAL', 'DISPATCH', '冷链权重', '冷链权重', '0', '1'),
    ('dispatch.weight_rider_level', '0.05', 'DECIMAL', 'DISPATCH', '骑手等级权重', '骑手等级权重', '0', '1'),
    ('dispatch.probation_max_tasks', '3', 'INT', 'DISPATCH', '新手并发上限', '新手并发上限', '1', '10'),
    ('dispatch.auto_reassign_enabled', 'true', 'BOOL', 'DISPATCH', '自动改派', '自动改派', NULL, NULL),
    ('routing.matrix_provider', 'HAVERSINE', 'STRING', 'ROUTING', '距离矩阵提供方', 'HAVERSINE/AMAP/TENCENT', NULL, NULL),
    ('routing.optimizer', 'GREEDY_2OPT', 'STRING', 'ROUTING', '路径优化器', 'GREEDY_2OPT/JSPRIT/AMAP', NULL, NULL),
    ('routing.detour_factor', '1.35', 'DECIMAL', 'ROUTING', 'Haversine 绕路系数', 'Haversine 绕路系数', '1.0', '2.5'),
    ('routing.matrix_cache_hours', '6', 'INT', 'ROUTING', '矩阵缓存有效期（小时）', '矩阵缓存有效期', '1', '168'),
    ('routing.solve_timeout_millis', '2000', 'INT', 'ROUTING', '求解超时（毫秒）', '求解超时', '100', '30000'),
    ('eta.ebike_speed_kmh', '15', 'DECIMAL', 'ETA', '电动自行车速度（km/h）', 'GB/T 46862 上限，不得调高', '5', '15'),
    ('eta.default_handoff_seconds', '180', 'INT', 'ETA', '默认交付时长（秒）', '无楼栋样本时的默认交付时长', '30', '1800'),
    ('eta.pickup_seconds', '300', 'INT', 'ETA', '门店取货耗时（秒）', '门店取货耗时', '0', '3600'),
    ('eta.protection_floor_seconds', '1200', 'INT', 'ETA', '保护时间下限（秒）', '保护时间下限', '0', '7200'),
    ('eta.quantile', '0.70', 'DECIMAL', 'ETA', '非对称分位数', '非对称分位数', '0.50', '0.99'),
    ('eta.display_as_range', 'true', 'BOOL', 'ETA', '顾客侧展示区间', '顾客侧展示区间', NULL, NULL),
    ('eta.range_span_minutes', '10', 'INT', 'ETA', '区间宽度（分钟）', '区间宽度', '1', '60'),
    ('tracking.report_interval_still_seconds', '60', 'INT', 'TRACKING', '静止采样间隔（秒）', '静止采样间隔', '5', '600'),
    ('tracking.report_interval_walking_seconds', '20', 'INT', 'TRACKING', '步行采样间隔（秒）', '步行采样间隔', '5', '600'),
    ('tracking.report_interval_riding_seconds', '10', 'INT', 'TRACKING', '骑行采样间隔（秒）', '骑行采样间隔', '3', '600'),
    ('tracking.upload_batch_seconds', '20', 'INT', 'TRACKING', '上传批次间隔（秒）', '上传批次间隔', '5', '300'),
    ('tracking.max_accuracy_meters', '100', 'INT', 'TRACKING', '最大可接受定位精度（米）', '超过此精度的点丢弃', '10', '1000'),
    ('tracking.retention_days', '90', 'INT', 'TRACKING', '轨迹保留天数', 'PIPL 保留期', '7', '365'),
    ('tracking.liveness_timeout_seconds', '120', 'INT', 'TRACKING', '掉线告警阈值（秒）', '掉线告警阈值', '30', '1800'),
    ('geofence.arrive_radius_meters', '80', 'INT', 'GEOFENCE', '到达围栏半径（米）', '到达围栏半径', '20', '500'),
    ('geofence.arrive_dwell_seconds', '30', 'INT', 'GEOFENCE', '到达停留判定（秒）', '到达停留判定', '5', '600'),
    ('fatigue.continuous_warn_seconds', '86400', 'INT', 'FATIGUE', '连续接单提醒阈值（秒）', '家庭自营场景已停用疲劳管控（设为 24 小时等同不触发）。若改为雇佣骑手运营，请按 GB/T 46862-2025 调回 14400（4 小时）', '3600', '86400'),
    ('fatigue.dispatch_pause_seconds', '0', 'INT', 'FATIGUE', '疲劳停派时长（秒）', '家庭自营场景已停用（0 表示不停派）。雇佣骑手场景应设为 1200（20 分钟）', '0', '7200'),
    ('fatigue.daily_confirm_seconds', '86400', 'INT', 'FATIGUE', '累计确认阈值（秒）', '家庭自营场景已停用。雇佣骑手场景应设为 28800（8 小时）', '3600', '86400'),
    ('fatigue.daily_force_seconds', '86400', 'INT', 'FATIGUE', '强制下班阈值（秒）', '家庭自营场景已停用（24 小时等同不触发，店主可连续工作不被踢下线）。雇佣骑手场景应设为 43200（12 小时）', '3600', '86400'),
    ('earning.base_amount', '300', 'INT', 'EARNING', '基础配送费（分）', '基础配送费', '0', '10000'),
    ('earning.distance_per_km_amount', '50', 'INT', 'EARNING', '每公里（分）', '每公里计价', '0', '1000'),
    ('earning.distance_free_meters', '1000', 'INT', 'EARNING', '免计里程（米）', '免计里程', '0', '10000'),
    ('earning.floor_per_floor_amount', '20', 'INT', 'EARNING', '每层（无电梯，分）', '每层爬楼补贴', '0', '500'),
    ('earning.weight_per_kg_amount', '10', 'INT', 'EARNING', '每公斤（超 5 kg，分）', '超重补贴', '0', '500'),
    ('earning.bad_weather_amount', '100', 'INT', 'EARNING', '恶劣天气补贴（分）', '恶劣天气补贴', '0', '5000'),
    ('earning.night_amount', '100', 'INT', 'EARNING', '夜间补贴（分）', '夜间补贴', '0', '5000'),
    ('earning.holiday_amount', '150', 'INT', 'EARNING', '节假日补贴（分）', '节假日补贴', '0', '5000'),
    ('earning.night_start_hour', '20', 'INT', 'EARNING', '夜间起始小时', '夜间起始', '0', '23'),
    ('delivery.require_verify_code', 'false', 'BOOL', 'DELIVERY', '送达强制核销码', '送达是否强制核销码', NULL, NULL),
    ('delivery.require_photo', 'true', 'BOOL', 'DELIVERY', '送达强制拍照', '送达是否强制拍照', NULL, NULL),
    ('weight.tolerance_percent', '3.0', 'DECIMAL', 'WEIGHT', '公平秤容差（%）', '公平秤容差', '0', '20'),
    ('weight.auto_refund_threshold_percent', '8.0', 'DECIMAL', 'WEIGHT', '自动退差价阈值（%）', '超此值自动退差价', '0', '50'),
    ('privacy.number_enabled', 'false', 'BOOL', 'PRIVACY', '隐私号开关', '隐私号开关', NULL, NULL),
    ('push.provider', 'NOOP', 'STRING', 'PUSH', '推送服务商', 'NOOP/JPUSH', NULL, NULL),
    ('score.overtime_penalty', '-2', 'INT', 'SCORE', '超时扣分', '超时扣分', '-20', '0'),
    ('score.on_time_reward', '1', 'INT', 'SCORE', '准时加分', '准时加分', '0', '10'),
    ('score.max', '120', 'INT', 'SCORE', '服务分上限', '服务分上限', '100', '200'),
    ('routing.lambda_late', '5.0', 'DECIMAL', 'ROUTING', '超时惩罚系数', '路径目标函数中超时的二次惩罚系数', '0', '100'),
    ('routing.lambda_cold', '8.0', 'DECIMAL', 'ROUTING', '冷链惩罚系数', '必须大于超时惩罚系数：化掉的冻品不可逆，晚到几分钟顾客大多能接受', '0', '100'),
    ('routing.lambda_early', '0.5', 'DECIMAL', 'ROUTING', '过早到达惩罚系数', '过早到达顾客可能不在家', '0', '100'),
    ('routing.exhaustive_max_stops', '8', 'INT', 'ROUTING', '精确求解站点上限', '不超过此值用全排列精确求解，超过用贪心加二opt', '4', '10'),
    ('eta.bad_weather_active', 'false', 'BOOL', 'ETA', '恶劣天气开关', '天气服务不可用时的兜底数据源', NULL, NULL),
    ('delivery.require_health_cert', 'false', 'BOOL', 'DELIVERY', '健康证过期是否禁止上班', '各地规定不一，拣货打包人员必须持证，骑手是否需要请咨询当地卫健委', NULL, NULL),
    ('dispatch.probation_max_distance_meters', '2000', 'INT', 'DISPATCH', '新手可接单最大里程（米）', '试用期骑手只参与总里程不超过此值的簇的竞争', '500', '20000'),
    ('dispatch.max_wave_weight_kg', '30', 'INT', 'DISPATCH', '单波次最大载重（千克）', '超出则拆波次，单任务波次豁免', '5', '100'),
    ('dispatch.min_score_threshold', '0', 'DECIMAL', 'DISPATCH', '派单最低得分阈值', '低于此分不派，留待下一轮；设为 0 表示不设门槛', '0', '1'),
    ('dispatch.alert_cooldown_seconds', '300', 'INT', 'DISPATCH', '运力预警冷却（秒）', '同类预警在冷却期内不重复推送', '60', '3600'),
    ('dispatch.reassign_max_count', '2', 'INT', 'DISPATCH', '单任务最大自动改派次数', '防止来回改派', '0', '5');
